frontEndCourses = {
    "HTML & CSS Basics": "frontend",
    "JavaScript for Beginners": "frontend",
    "Responsive Web Design": "frontend",
    "Advanced CSS Techniques": "frontend",
    "Introduction to Vue.js": "frontend",
    "React Essentials": "frontend",
    "Angular Fundamentals": "frontend",
    "Building Websites with Bootstrap": "frontend",
    "Sass and SCSS Crash Course": "frontend",
    "Modern JavaScript (ES6+)": "frontend",
    "Web Accessibility Best Practices": "frontend",
    "Webpack for Beginners": "frontend",
    "Tailwind CSS Basics": "frontend",
    "Advanced React Patterns": "frontend",
    "Building Progressive Web Apps": "frontend",
    "JavaScript DOM Manipulation": "frontend",
    "Front-End Web Performance": "frontend",
    "CSS Grid and Flexbox": "frontend",
    "React with TypeScript": "frontend",
    "JavaScript Event Handling": "frontend",
    "Intro to Gatsby.js": "frontend",
    "Testing React Applications": "frontend",
    "CSS Animations": "frontend",
    "Building Static Sites with Jekyll": "frontend",
    "GraphQL for Front-End Developers": "frontend",
    "Redux for State Management": "frontend",
    "Vue 3 Composition API": "frontend",
    "HTML5 APIs and Canvas": "frontend",
    "Creating Web Forms with HTML5": "frontend",
    "React Native for Web Developers": "frontend",
    "Building UI Components with Storybook": "frontend",
    "JavaScript Modules and Bundling": "frontend",
    "Angular with NgRx": "frontend",
    "Animating with GreenSock (GSAP)": "frontend",
    "Building with Material-UI": "frontend",
    "CSS Preprocessors (Sass, LESS)": "frontend",
    "Handling Asynchronous JavaScript": "frontend",
    "Next.js for React Developers": "frontend",
    "Web Security for Front-End Developers": "frontend",
    "JavaScript Functional Programming": "frontend",
    "CSS Variables and Custom Properties": "frontend",
    "Building SPAs with Vue Router": "frontend",
    "JavaScript Closures and Scope": "frontend",
    "Tailwind CSS Advanced Techniques": "frontend",
    "React Hooks Deep Dive": "frontend",
    "Front-End DevOps with Netlify": "frontend",
    "Building Websites with Eleventy": "frontend",
    "Understanding CSS Specificity": "frontend",
    "JavaScript Testing with Jest": "frontend",
    "Styled Components in React": "frontend"
}
